/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.idp.service;import org.junit.jupiter.api.Test;import static org.assertj.core.api.Assertions.assertThat;/**
                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                            */
class DocumentPostingGovernanceServiceTest{private final DocumentPostingGovernanceService service=new DocumentPostingGovernanceService();/**
                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                     */
@Test void postsVerifiedDocument(){var r=service.assess(new DocumentPostingGovernanceService.Request("D1",true,false,true,true,true,true,98,false,false));assertThat(r.decision()).isEqualTo(DocumentPostingGovernanceService.Decision.POST);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
@Test void rejectsInvalidDocument(){var r=service.assess(new DocumentPostingGovernanceService.Request("D2",false,true,false,false,false,false,99,false,false));assertThat(r.blockers()).hasSize(6);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
@Test void reviewsConfidenceAndHighValue(){var r=service.assess(new DocumentPostingGovernanceService.Request("D3",true,false,true,true,true,true,70,true,false));assertThat(r.actions()).hasSize(2);}}
