/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.idp.controller;import cn.zhuatech.idp.common.ApiResponse;import cn.zhuatech.idp.service.DocumentPostingGovernanceService;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                               */
@RestController @RequestMapping("/api/enterprise/idp")public class DocumentPostingGovernanceController{private final DocumentPostingGovernanceService service;/**
                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                             */
public DocumentPostingGovernanceController(DocumentPostingGovernanceService service){this.service=service;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
@PostMapping("/document-posting")public ApiResponse<DocumentPostingGovernanceService.Assessment>assess(@Valid @RequestBody DocumentPostingGovernanceService.Request request){return ApiResponse.ok(service.assess(request));}}
