/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.idp.service;import jakarta.validation.constraints.*;import org.springframework.stereotype.Service;import java.util.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Service public class DocumentPostingGovernanceService{/**
                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                        */
public Assessment assess(Request r){List<String>b=new ArrayList<>(),a=new ArrayList<>();if(!r.sourceAuthenticityVerified())b.add("单据来源真实性未验证");if(r.duplicateDetected())b.add("检测到重复单据");if(!r.documentTotalsBalanced())b.add("单据金额或税额勾稽不平");if(!r.masterDataMatched())b.add("供应商或客户主数据未匹配");if(!r.taxValidationPassed())b.add("税务校验未通过");if(!r.auditSnapshotStored())b.add("识别与校验审计快照未保存");if(!b.isEmpty()){a.add("拒绝入账并进入异常单据队列");return new Assessment(Decision.REJECT,b,a);}if(r.extractionConfidence()<90||(r.highValueDocument()&&!r.humanApprovalComplete())){if(r.extractionConfidence()<90)a.add("进入人工字段复核");if(r.highValueDocument()&&!r.humanApprovalComplete())a.add("取得高金额单据人工审批");return new Assessment(Decision.REVIEW,b,a);}a.add("允许入账并锁定原文、字段和校验版本");return new Assessment(Decision.POST,b,a);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         */
public record Request(@NotBlank String documentId,boolean sourceAuthenticityVerified,boolean duplicateDetected,boolean documentTotalsBalanced,boolean masterDataMatched,boolean taxValidationPassed,boolean auditSnapshotStored,@Min(0)@Max(100)int extractionConfidence,boolean highValueDocument,boolean humanApprovalComplete){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
public record Assessment(Decision decision,List<String>blockers,List<String>actions){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
public enum Decision{POST,REVIEW,REJECT}}
